version: '3.9'
name: 'mixql'

services:

#  demo:
#    image: mixql/demo:0.4
#    build:
#      context: dockerfiles/demo
#      args:
#        JAVA_VERSION: 8.0.362-tem
#        SCALA_VERSION: 3.2.2
#        SBT_VERSION: 1.8.2
#        MIXQL_APP_VERSION: 0.4.0-SNAPSHOT
#        MIXQL_GIT_COMMIT: 0.4.1
#        USER_UID: 1000
#        USER_GID: 1000
#        USER_NAME: sbt
#    domainname: mixql.loc
#    hostname: source
#    command: tree /mixql/app/ -L 2
#    volumes:
#      # folders from container
#      - mixql-app:/mixql/app/
#      - mixql-host-app:/mixql-host/app/
#      - mixql-src:/mixql/src/
#      - mixql-samples:/mixql/samples/
#      # shared folder from host
#      - ../mixql-platform/:/mixql-host/src/mixql-platform/
#      - ./samples/:/mixql-host/samples/
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#    env_file: ./settings.env
#    networks:
#      mixql-net:
#        ipv4_address: 172.18.0.254

  main:
    image: mixql/bigtop:0.4
    build:
      context: dockerfiles/bigtop-image
      args:
        JAVA_VERSION: 8.0.362-tem
        SCALA_VERSION: 3.2.2
        SBT_VERSION: 1.8.2
        MIXQL_APP_VERSION: 0.4.0-SNAPSHOT
        MIXQL_GIT_COMMIT: 0.4.1
        BIGTOP_GIT_COMMIT: release-3.2.0
        TZ: Europe/Moscow
#    command: /sbin/init
    domainname: mixql.loc
    hostname: main
    privileged: true
#    init: true
#    mem_limit: 4g
    ports:
      - 57000-57099:50070
      - 57500-57599:50075
      - 58601-58642:8042
      - 18000-18099:8088
      - 8081-8090:8081
      - 22888-23888:20888
      - 11000-11100:11000
    volumes:
      - ./dockerfiles/hosts:/etc/hosts
      # folders from container
      - mixql-app:/mixql/app/
      - mixql-host-app:/mixql-host/app/
      - mixql-src:/mixql/src/
      - mixql-samples:/mixql/samples/
      # shared folder from host
      - ../mixql-platform/:/mixql-host/src/mixql-platform/
      - ./samples/:/mixql-host/samples/
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    env_file:
      - ./settings.env
    networks:
      mixql-net:
        ipv4_address: 172.18.0.2

  node1:
    image: mixql/bigtop:0.4
    build:
      context: dockerfiles/bigtop-image
      args:
        JAVA_VERSION: 8.0.362-tem
        SCALA_VERSION: 3.2.2
        SBT_VERSION: 1.8.2
        MIXQL_APP_VERSION: 0.4.0-SNAPSHOT
        MIXQL_GIT_COMMIT: 0.4.1
        BIGTOP_GIT_COMMIT: release-3.2.0
        TZ: Europe/Moscow
#    command: /sbin/init
    domainname: mixql.loc
    hostname: node1
    privileged: true
#    mem_limit: 4g
    ports:
      - "58000-58099:50070"
      - "58600-58699:50075"
      - "19000-19099:8088"
      - "8181-8190:8081"
      - "20888-21888:20888"
      - "19888-19899:19888"
    volumes:
      - ./dockerfiles/hosts:/etc/hosts
      # folders from container
      - mixql-app:/mixql/app/
      - mixql-host-app:/mixql-host/app/
      - mixql-src:/mixql/src/
      - mixql-samples:/mixql/samples/
      # shared folder from host
      - ../mixql-platform/:/mixql-host/src/mixql-platform/
      - ./samples/:/mixql-host/samples/
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    env_file:
      - ./settings.env
    networks:
      mixql-net:
        ipv4_address: 172.18.0.3

#  netbird:
#    image: 'netbirdio/netbird:latest'
#    container_name: netbird
#    network_mode: host
#    hostname: netbird
#    cap_add:
#      - NET_ADMIN
#      - SYS_ADMIN
#      - SYS_RESOURCE
#    env_file: ./settings.env
##    environment:
##      - NB_SETUP_KEY=${NB_SETUP_KEY}
#    privileged: true
#    volumes:
#      - nb-volume:/etc/netbird

  tailscale:
    container_name: tailscaled
    image: tailscale/tailscale
    hostname: main
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /dev/net/tun:/dev/net/tun
      #- /home/io/docker_config/tailscale/varlib:/var/lib
      - ts-volume:/var/lib
      # https://github.com/tailscale/tailscale/issues/6849
      # add volume for the tailscaled.sock to be present on the host system
      # that's where caddy goes to communicate with tailscale
      #- /home/io/docker_config/tailscale/tmp:/tmp
    env_file: ./settings.env
    environment:
#       https://github.com/tailscale/tailscale/issues/4913#issuecomment-1186402307
#       we have to tell the container to put the state in the same folder
#       that way the state is saved on the host and survives reboot of the container
      - TS_STATE_DIR=/var/lib/tailscale
      # this have to be used only on the first time
      # after that, the state is saved in /var/lib/tailscale and the next line can be commented out
#      - TS_AUTH_KEY=${TS_AUTH_KEY}
#      - TS_ROUTES=172.18.0.0/24
#      - TS_HOSTNAME=tailscale
#      - TS_EXTRA_ARGS=--accept-routes --advertise-exit-node


networks:
  mixql-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24

volumes:
  # precompiled app
  mixql-app:
    driver: local
  # git in container
  mixql-src:
    driver: local
  # samples in container
  mixql-samples:
    driver: local
  # folder for compiled app
  mixql-host-app:
    driver: local
  # folder for tailscale.com
  ts-volume:
    driver: local
  # folder for netbird.io
  nb-volume:
    driver: local