= Getting started with SQLite
:navtitle: Getting started with SQLite
:keywords: sql, engine, SQLite, docker
:description: Testing MixQL with docker and SQLite
:source-language: console

////
Main links for editors:
- AsciiDoc syntax https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/
- Antora Pages https://docs.antora.org/antora/latest/page/
////

== What is this?

This is a simple https://docs.docker.com/get-docker/[docker] image hosting https://github.com/mixql/mixql-platform[mixql-platform] and https://www.sqlite.org/index.html[SQLite]. It can be used to easily spin up a SQLite database and test mixql queries.

== Running the container default mode

If no other options are passed, mixql-platform-demo script is started with hardcoded script.

[,subs="attributes+"]
----
docker run -it --rm --name demo  {image-mixql-demo}
# Equal to
docker run -it --rm --name demo  {image-mixql-demo} run
----

==== Expected result

[,subs="attributes+"]
----
########################################################
** Entrypoint for mixql-platform-demo-{app-version}-SNAPSHOT
########################################################
** Executing: ./mixql-platform-demo
** MIXQL_CLUSTER_BASE_PATH=/mixql/app/mixql-platform-demo-{app-version}-SNAPSHOT/bin
** DB=
** SCRIPT=
** Cmdline: /mixql/app/mixql-platform-demo-{app-version}-SNAPSHOT/bin/mixql-platform-demo

Mixql engine demo platform: parsing args
Mixql engine demo platform: initialising engines
Init functions for mixql context
Mixql engine demo platform: init Cluster context
...
----

To execute the mixql-platform-demo script and stay inside the bash after execution use the `bash` command after `run`:

[,subs="attributes+"]
----
docker run -it --rm --name demo {image-mixql-demo} run bash
----
==== Expected result
[,subs="attributes+"]
----
...
Broker thread finished...
sbt@0e0c062da510:/mixql/app/mixql-platform-demo-{app-version}-SNAPSHOT/bin$
----

To execute bash inside container without mixql-platform-demo script use only `bash`:

[,subs="attributes+"]
----
docker run -it --rm --name demo {image-mixql-demo} bash
----
==== Expected result
[,subs="attributes+"]
----
########################################################
** Entrypoint for mixql-platform-demo-{app-version}-SNAPSHOT
** Executing 'bash'
sbt@5e287ce3b721:/mixql$
----

To execute a particular script, pass its name in the environment variable SCRIPT:

[,subs="attributes+"]
----
$ docker run -it --rm --name demo  \
    -e SCRIPT=/mixql/src/mixql-platform/mixql-platform-demo/src/test/resources/test_simple_func.sql \
    {image-mixql-demo}
----
==== Expected result
[,subs="attributes+"]
----
########################################################
** Entrypoint for mixql-platform-demo-{app-version}-SNAPSHOT
########################################################
** Executing: ./mixql-platform-demo
** MIXQL_CLUSTER_BASE_PATH=/mixql/app/mixql-platform-demo-{app-version}-SNAPSHOT/bin
** DB=
** SCRIPT=/mixql/src/mixql-platform/mixql-platform-demo/src/test/resources/test_simple_func.sql
** Cmdline: /mixql/app/mixql-platform-demo-{app-version}-SNAPSHOT/bin/mixql-platform-demo  --sql-file /mixql/src/mixql-platform/mixql-platform-demo/src/test/resources/test_simple_func.sql
...
----

Similarly, to execute a particular script with a particular database from container, pass its names in the environment variables (SCRIPT and DB):

[,subs="attributes+"]
----
docker run -it --rm --name demo  \
    -e SCRIPT=/mixql/src/mixql-platform/mixql-platform-demo/src/test/resources/test_simple_func.sql \
    -e DB=/mixql/samples/db/sakila.db \
    {image-mixql-demo}
----

To set environment variables from single file use option `--env-file filename`
[,subs="attributes+"]
----
docker run -it --rm --name demo  \
    --env-file settings.env \
    {image-mixql-demo}
----

== Running container with an already existing database and script

The container can be started with a volume linked to it to persist data and scripts on the host:

[,subs="attributes+"]
----
docker run -it --rm --name demo  \
    -v "/$(pwd)/samples/:/mixql-host/samples/" \
    -e SCRIPT=/mixql-host/samples/scripts/test-titanic.sql \
    -e DB=/mixql-host/samples/db/titanic.db \
    {image-mixql-demo}
----

In this case, you can debug scripts on the host machine (/samples/scripts -> /mixql/samples/host/scripts), and use any SQLite dataset from the host machine (/samples/db -> /mixql/samples/host/db).


== Demo datasets

include::partial$datasets-sqlite.adoc[]


== Quick Start

Let's calculate the overall survival rate in titanic.db.
Firstly run simple SQLite script in `/samples/scripts/sqlite-test.sql` from host machine.

[,subs="attributes+"]
----
docker run -it --rm --name demo  \
    -v "/$(pwd)/samples/:/mixql-host/samples/"    \
    {image-mixql-demo} \
    sqlite3 /mixql-host/samples/db/titanic.db '.read /mixql-host/samples/scripts/sqlite-test.sql'
----

==== Expected result
[,subs="attributes+"]
----
########################################################
** Entrypoint for mixql-platform-demo-{app-version}-SNAPSHOT
** Executing custom command: 'sqlite3 /mixql-host/samples/db/titanic.db '.read /mixql-host/samples/scripts/sqlite-test.sql'
Not Survived|549|61.62 %|891
Survived|342|38.38 %|891
----

Next, create similar mixql script `/samples/scripts/mixql-test-titanic.sql` on host:
[,sql]
----
let engine "sqlite-local";
let a = (select
            case when f.survived = 1 then 'Survived' else 'Not Survived' end as Survival_status,
            count(*) as Survival_rate,
            printf("%.2f", 100.0 * count(*) / max(f.total_passeng)) || " %" as Percent,
            max(f.total_passeng) as Total_passengers
            from   (
                    select  count(*) over() as total_passeng,
                            t.*
                    from Observation t
                    ) f
            group by f.alive_id;
        )
print($a);
----

Try it on SQLite database
[,subs="attributes+"]
----
docker run -it --rm --name demo  \
    -v "/$(pwd)/samples/:/mixql-host/samples" \
    -e SCRIPT=/mixql-host/samples/scripts/mixql-test-titanic.sql \
    -e DB=/mixql-host/samples/db/titanic.db \
    {image-mixql-demo}
----

==== Expected result
[,subs="attributes+"]
----
########################################################
** Entrypoint for mixql-platform-demo-{app-version}-SNAPSHOT
########################################################
** Executing: ./mixql-platform-demo
...

----

== For developers

=== Folder structure

include::partial$mixql-tree-structure.adoc[]


=== Environment variables

include::partial$mixql-env.adoc[]

=== Rebuild image
If you want to change versions of apps or source code branch make new image (for example {image-mixql-demo}-local) with new settings (JAVA_VERSION, SCALA_VERSION, SBT_VERSION from https://sdkman.io/jdks[sdk]) and needed branch in GIT_COMMIT:

[,subs="attributes+"]
----
docker build --progress=plain \
    --build-arg JAVA_VERSION="8.0.362-tem" \
    --build-arg SCALA_VERSION="3.2.2" \
    --build-arg SBT_VERSION="1.8.2" \
    --build-arg MIXQL_APP_VERSION="0.3.0-SNAPSHOT" \
    --build-arg MIXQL_GIT_COMMIT="main" \
    -t {image-mixql-demo}-local ./dockerfiles/demo
----

or via docker-compose.yaml, change vars and start rebuild:
----
docker compose build demo
----

or with settings.env and one-liner for collectint of --build-arg from settings.env:
[,subs="attributes+"]
----
docker build --progress=plain \
    $(for i in `cat settings.env`; do out+="--build-arg $i " ; done; echo $out;out="") \
    -t {image-mixql-demo} ./dockerfiles/demo
----


=== Compile from host source
For quick change you can build app from local folder, map source code from host to container (src -> /app/src-host/mixql-platform/).
Compiled app will be placed to /app/mixql-platform-demo-{app-version}-SNAPSHOT

[,subs="attributes+"]
----
docker run -it --rm --name demo  \
    -v "/$(pwd)/../mixql-platform/:/mixql-host/src/mixql-platform/" \
    -v "/$(pwd)/app:/mixql-host/app/" \
    {image-mixql-demo} compile
----

=== Set versions before compiling

Before compiling you can install needed version of java, scala, sbt by environment variables via https://sdkman.io/jdks[sdk]:

[,subs="attributes+"]
----
docker run -it --rm --name demo  \
    -v "/$(pwd)/samples/:/mixql-host/samples/" \
    -v "/$(pwd)/../mixql-platform/:/mixql-host/src/mixql-platform/" \
    -v "/$(pwd)/app:/mixql-host/app" \
    -e SCRIPT=/mixql-host/samples/scripts/mixql-test-titanic.sql \
    -e DB=/mixql-host/samples/db/titanic.db \
    -e JAVA_VERSION=17.0.6-tem \
    {image-mixql-demo} compile bash
----

=== Prepared commands for container
* run - run precompiled app from /mixql/app;
* run-host - run compiled app from /mixql-host/app. Be sure app is ready to use (is compiled);
* compile - only compile app from /mixql-host/src;
* compile-run - compile /mixql-host/src and run app from /mixql-host/app.

Use  word `bash` after main command (run, compile...) to stay in bash after execution: `docker run -it --rm {image-mixql-demo}  compile bash`
