= Network Configuration
:navtitle: Network Configuration
:keywords: BigTop, docker, network, vpn, tailscale
:description: Network Configuration for Hadoop Cluster
:source-language: console

////
Main links for editors:
- AsciiDoc syntax https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/
- Antora Pages https://docs.antora.org/antora/latest/page/
////

== What is this?

We can use docker to work with a multi-node hadoop cluster that can be run in different environments: on your local computer, inside a WSL, inside a virtual machine, or on a remote server.

Each node contains its own set of services and ports to interact with them. Some of these ports are used by Hadoop’s daemons to communicate amongst themselves (to schedule jobs, replicate blocks, etc.). Others ports are listening directly to users, either via an interposed Java client, which communicates via internal protocols, or via plain old HTTP.

To facilitate network access to the cluster's internal network wherever it is running, we can use several approaches. The most convenient, but requiring additional customization, is access via VPN. We can also use the built-in SSH access and the usual docker commands.

=== Zero-configuration VPN
We can bring intranet on the internet with Zero-Config Mesh VPNs without having to worry about setting up a server like OpenVPN Server and spending days configuring it. Zero configuration networking allows you to automatically create a network of devices without having to manually configure a DHCP server, DNS services, or network settings for each device that you want to connect to that network.

We have these preconfigured Zero VPN services based on Wireguard:

- https://tailscale.com/blog/how-tailscale-works[Tailscale, window=_blank]
- https://docs.netbird.io/about-netbird/how-netbird-works[Netbird, window=_blank]

Docker compose file has sections for configuring VPN access to hadoop cluster. You need to select the desired VPN service and then configure appropriate service in the docker-compose file.

==== Tailscale

1. https://tailscale.com/kb/installation[Install Tailscale] on your workstation
2.

==== Netbird


=== Wireguard
You can use your own Wireguard service inside docker network.


== SSH

=== Ports
* Namenode: http://<dockerhadoop_IP_address>:9870/dfshealth.html#tab-overview
* History server: http://<dockerhadoop_IP_address>:8188/applicationhistory
* Datanode: http://<dockerhadoop_IP_address>:9864/
* Nodemanager: http://<dockerhadoop_IP_address>:8042/node
* Resource manager: http://<dockerhadoop_IP_address>:8088/